<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <LangVersion>preview</LangVersion>
    <RootNamespace>RyTuneX</RootNamespace>
    <ApplicationIcon>Assets/WindowIcon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
	<Platforms>x86;x64</Platforms>
	<RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>
    <PublishProfile>Properties\PublishProfiles\win-$(Platform).pubxml</PublishProfile>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWinUI>true</UseWinUI>
    <DefaultLanguage>en-US</DefaultLanguage>
    <AppxBundleAutoResourcePackageQualifiers>Scale|DXFeatureLevel</AppxBundleAutoResourcePackageQualifiers>
    <AppxDefaultResourceQualifiers>Language=en-US;ar-TN;de;es-ES;fr-FR;he-IL;it-IT;ja-JP;ko-KR;pt-BR;ru-RU;tr-TR;vi-VN;id-ID;zh-Hans;zh-Hant|Contrast=standard|Scale=200|HomeRegion=001|TargetSize=256|LayoutDirection=LTR|DXFeatureLevel=DX9|Configuration=|AlternateForm=|Platform=UAP</AppxDefaultResourceQualifiers>
    <EnableMsixTooling>true</EnableMsixTooling>
    <GenerateAppInstallerFile>False</GenerateAppInstallerFile>
    <AppxPackageSigningEnabled>False</AppxPackageSigningEnabled>
    <AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
    <AppxBundle>Always</AppxBundle>
    <WindowsPackageType>MSIX</WindowsPackageType>
    <SelfContained>true</SelfContained>
    <StartupObject>RyTuneX.Program</StartupObject>
    <AppxAutoIncrementPackageRevision>False</AppxAutoIncrementPackageRevision>
    <Version>1.8.0</Version>
    <Authors>Rayen Ghanmi</Authors>
    <GenerateTestArtifacts>False</GenerateTestArtifacts>
    <AppxBundlePlatforms>x86|x64</AppxBundlePlatforms>
    <AppxSymbolPackageEnabled>False</AppxSymbolPackageEnabled>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <NoWarn>$(NoWarn);CS0618</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\discord.png" />
    <None Remove="Assets\github.png" />
    <None Remove="Views\*.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Assets\WindowIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)' != 'Debug'">
      <AppxPackageCompressionEnabled>true</AppxPackageCompressionEnabled>
      <Deterministic>true</Deterministic>
      <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
      <EnableXbfGeneration>true</EnableXbfGeneration>
      <OptimizeImplicitStyles>true</OptimizeImplicitStyles>
      <GeneratePriDebugFiles>false</GeneratePriDebugFiles>
      <GenerateDocumentationFile>false</GenerateDocumentationFile>
      <DebuggerSupport>false</DebuggerSupport>
      <StripSymbols>true</StripSymbols>
      <EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
      <EnableBindingDiagnostics>false</EnableBindingDiagnostics>
	  <PublishTrimmed>true</PublishTrimmed>
      <TrimMode>partial</TrimMode>
      <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>

  <PropertyGroup Condition="('$(Platform)' == 'x64' or '$(RuntimeIdentifier)' == 'win-x64') and '$(Configuration)' != 'Debug'">
      <PlatformTarget>x64</PlatformTarget>
      <PublishAot Condition="'$(UapAppxPackageBuildMode)' != '' or '$(AppxBundle)' == 'Always'">false</PublishAot>
      <PublishAot Condition="'$(PublishAot)' == ''">true</PublishAot>
      <PublishTrimmed>true</PublishTrimmed>
      <PublishReadyToRun Condition="'$(PublishAot)' != 'true'">true</PublishReadyToRun>
      <PublishReadyToRun Condition="'$(PublishAot)' == 'true'">false</PublishReadyToRun>
      <IncludePublishItemsOutputGroup Condition="'$(PublishAot)' == 'true'">true</IncludePublishItemsOutputGroup>
  </PropertyGroup>

  <PropertyGroup Condition="('$(Platform)' == 'x86' or '$(RuntimeIdentifier)' == 'win-x86') and '$(Configuration)' != 'Debug'">
      <PlatformTarget>x86</PlatformTarget>
      <PublishAot>false</PublishAot>
      <PublishTrimmed>true</PublishTrimmed>
      <TrimMode>partial</TrimMode>
      <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>

  <PropertyGroup Condition="'$(PublishAot)' == 'true'">
      <IlcUseEnvironmentalTools Condition="'$(IlcUseEnvironmentalTools)' == '' and Exists('C:\Program Files\Microsoft Visual Studio\18\Community\VC\Tools\MSVC\14.44.35207\bin\HostX64\x64\link.exe')">true</IlcUseEnvironmentalTools>
      <CppLinker Condition="'$(CppLinker)' == '' and Exists('C:\Program Files\Microsoft Visual Studio\18\Community\VC\Tools\MSVC\14.44.35207\bin\HostX64\x64\link.exe')">C:\Program Files\Microsoft Visual Studio\18\Community\VC\Tools\MSVC\14.44.35207\bin\HostX64\x64\link.exe</CppLinker>
      <CppLibCreator Condition="'$(CppLibCreator)' == '' and Exists('C:\Program Files\Microsoft Visual Studio\18\Community\VC\Tools\MSVC\14.44.35207\bin\HostX64\x64\lib.exe')">C:\Program Files\Microsoft Visual Studio\18\Community\VC\Tools\MSVC\14.44.35207\bin\HostX64\x64\lib.exe</CppLibCreator>
  </PropertyGroup>

  <ItemGroup Condition="'$(PublishAot)' == 'true' and '$(IlcUseEnvironmentalTools)' == 'true'">
      <AdditionalNativeLibraryDirectories Include="C:\Program Files\Microsoft Visual Studio\18\Community\VC\Tools\MSVC\14.44.35207\lib\x64" />
      <AdditionalNativeLibraryDirectories Include="C:\Program Files (x86)\Windows Kits\10\Lib\10.0.26100.0\um\x64" />
      <AdditionalNativeLibraryDirectories Include="C:\Program Files (x86)\Windows Kits\10\Lib\10.0.26100.0\ucrt\x64" />
  </ItemGroup>

  <Target Name="DeduplicateAotMsixPayload"
          BeforeTargets="_ComputeAppxPackagePayload"
          Condition="'$(PublishTrimmed)' == 'true'">
    <CallTarget Targets="__BackCalculateOptimizationInputAssemblies">
      <Output TaskParameter="TargetOutputs" ItemName="_OptimizationInputsToRemove"/>
    </CallTarget>
    <ItemGroup>
      <_PackagingOutputsUnexpanded Remove="@(_OptimizationInputsToRemove)" />
      <_PackagingOutputsOutsideLayout Remove="@(_OptimizationInputsToRemove)" />
    </ItemGroup>
  </Target>

  <ItemGroup>
      <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
      <PackageReference Include="CommunityToolkit.WinUI.Behaviors" Version="8.2.251219" />
      <PackageReference Include="CommunityToolkit.WinUI.Controls.Primitives" Version="8.2.251219" />
      <PackageReference Include="CommunityToolkit.WinUI.Controls.Segmented" Version="8.2.251219" />
      <PackageReference Include="CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.2.251219" />
      <PackageReference Include="DevWinUI" Version="10.1.0" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
      <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.3.1" />
      <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="10.0.10" />
      <PackageReference Include="System.Drawing.Common" Version="10.0.10" />
      <PackageReference Include="System.Formats.Nrbf" Version="10.0.10" />
      <PackageReference Include="System.Management" Version="10.0.10" />
      <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.10" />
      <PackageReference Include="Vortice.D3DCompiler" Version="3.8.3" />
      <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
      <PackageReference Include="Vortice.DXGI" Version="3.8.3" />
      <PackageReference Include="WinUIEx" Version="2.9.2" />
  </ItemGroup>
  
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\WindowIcon.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Controls\UsageGraph.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Helpers\OptimizeSystemHelper.cs" />
    <EmbeddedResource Include="Helpers\OptimizationOptions.cs" />
  </ItemGroup>

</Project>
